server_names = ['ProviderName', 'ProviderNamev6-Ifexisted']
listen_addresses = ['127.0.0.1:53', '[::1]:53']
max_clients = 250
force_tcp = false
timeout = 2000
keepalive = 30

# Load-balancing strategy: 'p2' (default), 'ph', 'fastest' or 'random'
lb_strategy = 'fastest'
fallback_resolver = '94.140.14.14:53'
ignore_system_dns = true
netprobe_timeout = 30
cache = false
cache_size = 512
cache_min_ttl = 90
cache_max_ttl = 1800
cache_neg_min_ttl = 2
cache_neg_max_ttl = 6

# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = true

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = false

[static]
## Publickey: YOURPUBKEY
[static.'ProviderName']
stamp = 'sdns://YOUR-DNS-STAMPS'
[static.'ProviderNamev6-Ifexisted']
stamp = 'sdns://YOUR-DNS-STAMPS'
